### ISSUE TITLE
v0.7.7 - AttributeError: 'PRand' object has no attribute 'name'

### ISSUE THREAD

**Issue by zbdm** [Qirky/FoxDot#135]
This `s1 >> pulse(PRand([5,8]))` give me this error : 
Only with v0.7.7, works fine with 0.7.4

`Traceback (most recent call last):
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Code\main_lib.py", line 110, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Players.py", line 165, in __rshift__
    self.__rshift__(*args, **kwargs)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Players.py", line 373, in __rshift__
    self.update(other.name, other.degree, **other.kwargs)
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Players.py", line 811, in update
    self.playstring = str(degree) # this doesn't work for var!
  File "C:\Users\sebas\FoxDot\FoxDot\lib\Patterns\Main.py", line 1251, in __repr__
    return "{}({})".format(self.name, self.data)
AttributeError: 'PRand' object has no attribute 'name'
`

**Comment by Qirky** [comment]
Thanks for catching this - it's been fixed now :)
